import type { QuestionCategory } from '../types/ai.types'

export const questionCategories: QuestionCategory[] = [
  {
    id: 'financial',
    label: 'Financial Performance',
    icon: 'TrendingUp',
    questions: [
      {
        id: 'fp-1',
        text: 'What is our revenue trend over the past 12 months?',
        category: 'financial',
        keywords: ['revenue', 'trend', 'growth', 'income'],
        route: '/financials',
        pageName: 'Group Financials',
        decisionType: 'monitor',
      },
      {
        id: 'fp-2',
        text: 'How does our P&L compare to budget YTD?',
        category: 'financial',
        keywords: ['pnl', 'budget', 'variance', 'actual', 'profit', 'loss'],
        route: '/financials',
        pageName: 'Group Financials',
        decisionType: 'monitor',
      },
      {
        id: 'fp-3',
        text: 'Break down revenue by fee category and show growth rates',
        category: 'financial',
        keywords: ['revenue', 'fee', 'breakdown', 'custody', 'transaction', 'securities lending'],
        decisionType: 'diagnose',
      },
      {
        id: 'fp-4',
        text: 'What is our expense run rate and where are the largest variances?',
        category: 'financial',
        keywords: ['expense', 'cost', 'run rate', 'variance', 'budget'],
        decisionType: 'diagnose',
      },
      {
        id: 'fp-5',
        text: 'Show profitability by business segment',
        category: 'financial',
        keywords: ['segment', 'profitability', 'cis', 'wealth', 'asset management'],
        route: '/business-economics',
        pageName: 'Business Economics',
        decisionType: 'compare',
      },
      {
        id: 'fp-6',
        text: 'What is our EPS trend and how does it compare to consensus?',
        category: 'financial',
        keywords: ['eps', 'earnings', 'per share', 'consensus', 'estimate'],
        decisionType: 'monitor',
      },
    ],
  },
  {
    id: 'capital',
    label: 'Capital & Liquidity',
    icon: 'Shield',
    questions: [
      {
        id: 'cl-1',
        text: 'What is our current CET1 ratio and headroom to requirements?',
        category: 'capital',
        keywords: ['cet1', 'capital', 'ratio', 'headroom', 'regulatory'],
        route: '/alm',
        pageName: 'ALM & Treasury',
        decisionType: 'monitor',
      },
      {
        id: 'cl-2',
        text: 'Show LCR and NSFR trends with regulatory thresholds',
        category: 'capital',
        keywords: ['lcr', 'nsfr', 'liquidity', 'coverage', 'stable funding'],
        route: '/alm',
        pageName: 'ALM & Treasury',
        decisionType: 'monitor',
      },
      {
        id: 'cl-3',
        text: 'How would a 200bp rate shock impact our capital position?',
        category: 'capital',
        keywords: ['rate shock', 'stress', 'capital', 'sensitivity', 'interest rate'],
        decisionType: 'forecast',
      },
      {
        id: 'cl-4',
        text: 'What is our HQLA composition and how has it shifted?',
        category: 'capital',
        keywords: ['hqla', 'high quality liquid assets', 'composition', 'level 1', 'level 2'],
        decisionType: 'monitor',
      },
      {
        id: 'cl-5',
        text: 'Analyze our RWA composition and identify optimization opportunities',
        category: 'capital',
        keywords: ['rwa', 'risk weighted', 'credit', 'market', 'operational'],
        decisionType: 'optimize',
      },
    ],
  },
  {
    id: 'client',
    label: 'Client Economics',
    icon: 'Users',
    questions: [
      {
        id: 'ce-1',
        text: 'Who are our top 20 clients by revenue and what is concentration risk?',
        category: 'client',
        keywords: ['top clients', 'concentration', 'revenue', 'risk'],
        route: '/clients',
        pageName: 'Client Economics',
        decisionType: 'monitor',
      },
      {
        id: 'ce-2',
        text: 'What is our client retention rate and which segments are at risk?',
        category: 'client',
        keywords: ['retention', 'churn', 'attrition', 'client loss'],
        route: '/clients',
        pageName: 'Client Economics',
        decisionType: 'monitor',
      },
      {
        id: 'ce-3',
        text: 'Analyze revenue per client by segment and identify growth opportunities',
        category: 'client',
        keywords: ['revenue per client', 'segment', 'wallet share', 'growth'],
        decisionType: 'optimize',
      },
      {
        id: 'ce-4',
        text: 'What is the fee margin by client segment and how does it compare to targets?',
        category: 'client',
        keywords: ['fee margin', 'basis points', 'client segment', 'pricing'],
        decisionType: 'compare',
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operational Efficiency',
    icon: 'Settings',
    questions: [
      {
        id: 'oe-1',
        text: 'What is our cost-to-income ratio trend and path to the 65% target?',
        category: 'operations',
        keywords: ['cost to income', 'efficiency', 'ratio', 'target'],
        route: '/operations',
        pageName: 'Finance Operations',
        decisionType: 'monitor',
      },
      {
        id: 'oe-2',
        text: 'How does STP rate compare to our 97% target?',
        category: 'operations',
        keywords: ['stp', 'straight through processing', 'automation', 'target'],
        route: '/operations',
        pageName: 'Finance Operations',
        decisionType: 'monitor',
      },
      {
        id: 'oe-3',
        text: 'What is our revenue per FTE and how does it benchmark?',
        category: 'operations',
        keywords: ['revenue per employee', 'fte', 'productivity', 'benchmark'],
        decisionType: 'compare',
      },
      {
        id: 'oe-4',
        text: 'What are the top technology investments by ROI?',
        category: 'operations',
        keywords: ['technology', 'roi', 'investment', 'automation', 'payback'],
        decisionType: 'optimize',
      },
    ],
  },
  {
    id: 'risk',
    label: 'Risk & Compliance',
    icon: 'AlertTriangle',
    questions: [
      {
        id: 'rc-1',
        text: 'What is our current risk appetite utilization across all categories?',
        category: 'risk',
        keywords: ['risk appetite', 'utilization', 'limit', 'credit', 'market', 'operational'],
        route: '/risk-compliance',
        pageName: 'Risk & Compliance',
        decisionType: 'monitor',
      },
      {
        id: 'rc-2',
        text: 'Are there any overdue regulatory remediation items?',
        category: 'risk',
        keywords: ['regulatory', 'remediation', 'overdue', 'finding', 'examination'],
        route: '/risk-compliance',
        pageName: 'Risk & Compliance',
        decisionType: 'monitor',
      },
      {
        id: 'rc-3',
        text: 'Summarize our credit risk exposure by loan segment',
        category: 'risk',
        keywords: ['credit risk', 'loan', 'npl', 'charge off', 'allowance'],
        decisionType: 'diagnose',
      },
      {
        id: 'rc-4',
        text: 'What is our cybersecurity posture and incident trend?',
        category: 'risk',
        keywords: ['cybersecurity', 'security score', 'incidents', 'vulnerability', 'phishing'],
        route: '/risk-compliance',
        pageName: 'Risk & Compliance',
        decisionType: 'monitor',
      },
    ],
  },
  {
    id: 'peer',
    label: 'Market & Peer',
    icon: 'BarChart3',
    questions: [
      {
        id: 'mp-1',
        text: 'How do we rank vs. peers on ROE, efficiency, and AUC?',
        category: 'peer',
        keywords: ['peer', 'comparison', 'ranking', 'roe', 'efficiency', 'auc'],
        route: '/external-positioning',
        pageName: 'External Positioning',
        decisionType: 'compare',
      },
      {
        id: 'mp-2',
        text: 'How does our valuation compare to peer group?',
        category: 'peer',
        keywords: ['valuation', 'pe ratio', 'price to book', 'market cap', 'peer'],
        route: '/external-positioning',
        pageName: 'External Positioning',
        decisionType: 'compare',
      },
      {
        id: 'mp-3',
        text: 'Create a competitive scorecard across all key metrics',
        category: 'peer',
        keywords: ['competitive', 'scorecard', 'benchmark', 'peer', 'ranking'],
        decisionType: 'compare',
      },
      {
        id: 'mp-4',
        text: 'What is the news sentiment trend for us vs. peers?',
        category: 'peer',
        keywords: ['news', 'sentiment', 'analyst', 'headline', 'peer'],
        decisionType: 'monitor',
      },
    ],
  },
  {
    id: 'forward',
    label: 'Forward-Looking',
    icon: 'Compass',
    questions: [
      {
        id: 'fl-1',
        text: 'Are we on track for 2025 strategic targets?',
        category: 'forward',
        keywords: ['strategic', 'target', 'progress', 'on track', '2025'],
        route: '/planning',
        pageName: 'Planning & Strategy',
        decisionType: 'monitor',
      },
      {
        id: 'fl-2',
        text: 'What are the biggest risks to achieving our ROE target?',
        category: 'forward',
        keywords: ['risk', 'roe', 'target', 'driver', 'gap'],
        decisionType: 'diagnose',
      },
      {
        id: 'fl-3',
        text: 'Show scenario analysis for a recession scenario',
        category: 'forward',
        keywords: ['scenario', 'recession', 'stress test', 'downturn'],
        route: '/planning',
        pageName: 'Planning & Strategy',
        decisionType: 'forecast',
      },
      {
        id: 'fl-4',
        text: 'What is the sensitivity of NII to rate changes?',
        category: 'forward',
        keywords: ['nii', 'sensitivity', 'interest rate', 'net interest income', 'nim'],
        route: '/alm',
        pageName: 'ALM & Treasury',
        decisionType: 'forecast',
      },
      {
        id: 'fl-5',
        text: 'What would it take to close the ROE gap to our target?',
        category: 'forward',
        keywords: ['roe', 'gap', 'target', 'bridge', 'improvement'],
        decisionType: 'optimize',
      },
    ],
  },
]

// Flatten all questions for search
export const allQuestions = questionCategories.flatMap((cat) => cat.questions)
